# docker-compose.yml
# We should let the IP address fixed, because the DNS do not work correctly when joining L1 nodes
version: '3'
services:
  dag-l1-1:
    container_name: dag-l1-1
    build:
      context: ../../../source
      dockerfile: ../infra/docker/dag-l1/initial-validator/Dockerfile
    image: dag-l1-initial-validator
    environment:
      - CL_PUBLIC_HTTP_PORT=9000
      - CL_P2P_HTTP_PORT=9001
      - CL_CLI_HTTP_PORT=9002
      - CL_L0_PEER_HTTP_HOST=global-l0-1
      - CL_L0_PEER_HTTP_PORT=9000
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
    volumes:
      - ../shared/jars:/code/jars/
    ports:
      - '9100:9000'
      - '9101:9001'
      - '9102:9002'
    networks:
      custom-network:
        ipv4_address: 172.50.0.10
    command: >
      sh -c "cp dag-l1.jar jars/dag-l1.jar && \
             cp cl-wallet.jar jars/cl-wallet.jar && \
             java -jar dag-l1.jar run-initial-validator --ip 172.50.0.10"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://dag-l1-1:9000/cluster/info" ]
      interval: 10s
      timeout: 10s
      retries: 10
  dag-l1-2:
    container_name: dag-l1-2
    build:
      context: ../../../source
      dockerfile: ../infra/docker/dag-l1/node-2/Dockerfile
    image: dag-l1-validator-node-2
    depends_on:
      dag-l1-1:
        condition: service_healthy
    environment:
      - CL_PUBLIC_HTTP_PORT=9000
      - CL_P2P_HTTP_PORT=9001
      - CL_CLI_HTTP_PORT=9002
      - CL_L0_PEER_HTTP_HOST=global-l0-1
      - CL_L0_PEER_HTTP_PORT=9000
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
    volumes:
      - ../shared/jars:/code/jars/
    ports:
      - '9200:9000'
      - '9201:9001'
      - '9202:9002'
    networks:
      custom-network:
        ipv4_address: 172.50.0.11
    command: >
      sh -c "cp jars/cl-wallet.jar genesis/cl-wallet.jar && \
      
             cd genesis/ && \
      
             export CL_KEYSTORE=$${CL_KEYSTORE_GENESIS} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_GENESIS} && \
             export CL_PASSWORD=$${CL_PASSWORD_GENESIS} && \
             cd ../ && \
      
             export CL_KEYSTORE=$${CL_KEYSTORE_NODE_2} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_NODE_2} && \
             export CL_PASSWORD=$${CL_PASSWORD_NODE_2} && \
      
             cp jars/dag-l1.jar dag-l1.jar && \
             java -jar dag-l1.jar run-validator --ip 172.50.0.11"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://dag-l1-2:9000/metrics" ]
      interval: 10s
      timeout: 10s
      retries: 10
  dag-l1-3:
    container_name: dag-l1-3
    build:
      context: ../../../source
      dockerfile: ../infra/docker/dag-l1/node-3/Dockerfile
    image: dag-l1-validator-node-3
    depends_on:
      dag-l1-1:
        condition: service_healthy
    environment:
      - CL_PUBLIC_HTTP_PORT=9000
      - CL_P2P_HTTP_PORT=9001
      - CL_CLI_HTTP_PORT=9002
      - CL_L0_PEER_HTTP_HOST=global-l0-1
      - CL_L0_PEER_HTTP_PORT=9000
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
    volumes:
      - ../shared/jars:/code/jars/
    ports:
      - '9300:9000'
      - '9301:9001'
      - '9302:9002'
    networks:
      custom-network:
        ipv4_address: 172.50.0.12
    command: >
      sh -c "cp jars/cl-wallet.jar genesis/cl-wallet.jar && \

             cd genesis/ && \

             export CL_KEYSTORE=$${CL_KEYSTORE_GENESIS} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_GENESIS} && \
             export CL_PASSWORD=$${CL_PASSWORD_GENESIS} && \

             cd ../ && \

             export CL_KEYSTORE=$${CL_KEYSTORE_NODE_3} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_NODE_3} && \
             export CL_PASSWORD=$${CL_PASSWORD_NODE_3} && \

             cp jars/dag-l1.jar dag-l1.jar && \
             java -jar dag-l1.jar run-validator --ip 172.50.0.12"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://dag-l1-3:9000/metrics" ]
      interval: 10s
      timeout: 10s
      retries: 10
networks:
  custom-network:
    external: true