# docker-compose.yml
# We should let the IP address fixed, because the DNS do not work correctly when joining L1 nodes
version: '3'
services:
  global-l0-1:
    container_name: global-l0-1
    build:
      context: ../../../source
      dockerfile: ../infra/docker/global-l0/Dockerfile
    image: global-l0
    environment:
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
      - CL_ENV=dev
      - SHOULD_RESET_GENESIS_FILE=${SHOULD_RESET_GENESIS_FILE}
      - FORCE_ROLLBACK=${FORCE_ROLLBACK}
    volumes:
      - ../shared/jars:/code/jars/
      - ../../../source/global-l0/tessellation:/code/codebase/tessellation
      - ../../../source/global-l0/genesis:/code/genesis/.
      - ../../../scripts/start_containers/start_genesis_global.sh:/code/start_genesis_global.sh
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      custom-network:
        ipv4_address: 172.50.0.5
    command: >
      sh -c 'chmod a+rwx start_genesis_global.sh && ./start_genesis_global.sh'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://global-l0-1:9000/cluster/info" ]
      interval: 10s
      timeout: 10s
      retries: 10
networks:
  custom-network:
    external: true